### ISSUE TITLE
Back port to PHP >= 7.1

### ISSUE THREAD

**Issue by hollodotme** [openmetrics-php/exposition-text#1]
## Expected Behavior

The library also installs/works on PHP 7.1.

## Actual Behavior

The library only installs/works on PHP >= 7.2

## Specifications

- Package version: v0.1.0

## Further comments

Back porting to PHP 7.1 was originally requested [via Twitter](https://twitter.com/s7anley/status/1059890553645662209)

/cc @s7anley

**Comment by s7anley** [comment]
👍 I will test it out.
