### ISSUE TITLE
Remove dependency on psr/http-message

### ISSUE THREAD

**Issue by m-nic** [openmetrics-php/exposition-text#12]
I don't think this package should rely on psr/http-message. 
It should be the client responsibility to expose the metrics. 
At most some recommendations/examples can be provided.

Most likely many of the clients already use a framework that uses the psr7, meaning they should just hook it up themselves - also this can bring in conflicts for frameworks using psr/http-message: ^2.0 dependency.

Or as in my case, I have to bring in an unwanted dependency because I just want to dump the metrics directly to a file.

What do you think?

**Comment by hollodotme** [comment]
I'm always in for reduction of dependencies. I'll have a look, if we can leave it out.

**Comment by hollodotme** [comment]
@m-nic I agree with you and removed the classes `HttpResponse` and `OutputStream` which implemented `psr/http-message` interfaces. Thus removed the composer dependency as well.

Will be released in #13
