### ISSUE TITLE
_total suffix for counters does not work for HELP and TYPE

### ISSUE THREAD

**Issue by theravel** [openmetrics-php/exposition-text#5]
## Description
Counters add automatically `_total` suffix to metric itself, but it does not work for TYPE and HELP, so in fact you get descrepancy between metric definition and actual name. I think this commit must be reverted, people should be able to manage metric names without any magic in code: https://github.com/openmetrics-php/exposition-text/commit/78bc5df29253136fdd8e9200f68dd913393b6d23

## Expected Behavior
```
# TYPE your_metric_name_total counter
# HELP your_metric_name_total A helpful description of your measurement.
your_metric_name_total 1.000000
```

## Actual Behavior
As described in README (and really works this way):
```
# TYPE your_metric_name counter
# HELP your_metric_name A helpful description of your measurement.
your_metric_name_total 1.000000
```

## Steps to Reproduce the Problem
Any of examples here: https://github.com/openmetrics-php/exposition-text/blob/master/examples/counters.php

**Comment by hollodotme** [comment]
Thank you for the issue, @theravel.

But the implementation is actually correct.

Have a look at the [specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes) and test cases (https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/counter_exemplars/metrics) at OpenMetrics.
