### ISSUE TITLE
8.1 Deprecation notice(s)

### ISSUE THREAD

**Issue by mgrundkoetter** [openmetrics-php/exposition-text#8]
## Expected Behavior

Should work on PHP 8.1+ :-)

## Actual Behavior

Deprecated: Return type of OpenMetricsPhp\Exposition\Text\Collections\LabelCollection::getIterator(): iterable should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/openmetrics-php/exposition-text/src/Collections/LabelCollection.php on line 65

There are probably some more.

## Steps to Reproduce the Problem

1. Use lib with PHP 8.1
2. do something with labels
3. recognize deprecation warning

## Specifications

- Package version: 0.3.1
- PHP version: 8.1.
- Platform/OS: Docker
- Subsystem: php:8.1-apache

**Comment by m-nic** [comment]
Hi,
Same issue is encountered on several classes for php 8.3.
Is this repo abandoned?

**Comment by hollodotme** [comment]
It's not abandoned. There is just not enough time on my end at the moment. Any help - in the meaning of a Pull Request Contribution - is welcome. 🙏

**Comment by m-nic** [comment]
> It's not abandoned. There is just not enough time on my end at the moment. Any help - in the meaning of a Pull Request Contribution - is welcome. 🙏

See: https://github.com/openmetrics-php/exposition-text/pull/11

**Comment by hollodotme** [comment]
Will be fixed with #13
